<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="12" passed="12" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-31T11:35:21 IST" name="Lambda Test Suite" finished-at="2023-08-31T11:36:56 IST" duration-ms="94485">
    <groups>
    </groups>
    <test started-at="2023-08-31T11:35:21 IST" name="Lambda Test01" finished-at="2023-08-31T11:35:55 IST" duration-ms="33708">
      <class name="com.LambdaTestFinal.TestNgTest1">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.LambdaTestFinal.TestNgTest1@36ebc363]" started-at="2023-08-31T11:35:21 IST" name="setUp" finished-at="2023-08-31T11:35:46 IST" duration-ms="24318" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[88.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Windows 10]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Test_01]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="Test_Scenario_01(java.lang.String)[pri:0, instance:com.LambdaTestFinal.TestNgTest1@36ebc363]" started-at="2023-08-31T11:35:46 IST" name="Test_Scenario_01" finished-at="2023-08-31T11:35:47 IST" duration-ms="1310" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://www.lambdatest.com/selenium-playground/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_Scenario_01 -->
        <test-method signature="Test_Scenario_02()[pri:0, instance:com.LambdaTestFinal.TestNgTest1@36ebc363]" started-at="2023-08-31T11:35:47 IST" name="Test_Scenario_02" finished-at="2023-08-31T11:35:51 IST" duration-ms="3988" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_Scenario_02 -->
        <test-method signature="Test_Scenario_03(java.lang.String)[pri:0, instance:com.LambdaTestFinal.TestNgTest1@36ebc363]" started-at="2023-08-31T11:35:51 IST" name="Test_Scenario_03" finished-at="2023-08-31T11:35:54 IST" duration-ms="3258" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://www.lambdatest.com/selenium-playground/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_Scenario_03 -->
        <test-method is-config="true" signature="tearDown(java.lang.String)[pri:0, instance:com.LambdaTestFinal.TestNgTest1@36ebc363]" started-at="2023-08-31T11:35:54 IST" name="tearDown" finished-at="2023-08-31T11:35:55 IST" duration-ms="764" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test_01]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
 ****Title Not matched**** expected [Selenium Grid Online | Run Selenium Test On Cloud--] but found [Selenium Grid Online | Run Selenium Test On Cloud],
 **** Check Box already selected  **** expected [false] but found [true],
**** Alert Box message Not Matched! ****** expected [I am an alert box!--] but found [I am an alert box!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
 ****Title Not matched**** expected [Selenium Grid Online | Run Selenium Test On Cloud--] but found [Selenium Grid Online | Run Selenium Test On Cloud],
 **** Check Box already selected  **** expected [false] but found [true],
**** Alert Box message Not Matched! ****** expected [I am an alert box!--] but found [I am an alert box!]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.LambdaTestFinal.TestNgTest1.tearDown(TestNgTest1.java:149)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassConfigurations(TestMethodWorker.java:229)
at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:215)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:131)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.LambdaTestFinal.TestNgTest1 -->
    </test> <!-- Lambda Test01 -->
    <test started-at="2023-08-31T11:35:55 IST" name="Lambda Test02" finished-at="2023-08-31T11:36:13 IST" duration-ms="17462">
      <class name="com.LambdaTestFinal.TestNgTest1">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.LambdaTestFinal.TestNgTest1@4b2bac3f]" started-at="2023-08-31T11:35:55 IST" name="setUp" finished-at="2023-08-31T11:36:04 IST" duration-ms="8608" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[MicrosoftEdge]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[87.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[macOS Sierra]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Test_02]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="Test_Scenario_01(java.lang.String)[pri:0, instance:com.LambdaTestFinal.TestNgTest1@4b2bac3f]" started-at="2023-08-31T11:36:04 IST" name="Test_Scenario_01" finished-at="2023-08-31T11:36:06 IST" duration-ms="2164" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://www.lambdatest.com/selenium-playground/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_Scenario_01 -->
        <test-method signature="Test_Scenario_02()[pri:0, instance:com.LambdaTestFinal.TestNgTest1@4b2bac3f]" started-at="2023-08-31T11:36:06 IST" name="Test_Scenario_02" finished-at="2023-08-31T11:36:09 IST" duration-ms="3122" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_Scenario_02 -->
        <test-method signature="Test_Scenario_03(java.lang.String)[pri:0, instance:com.LambdaTestFinal.TestNgTest1@4b2bac3f]" started-at="2023-08-31T11:36:09 IST" name="Test_Scenario_03" finished-at="2023-08-31T11:36:12 IST" duration-ms="2713" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://www.lambdatest.com/selenium-playground/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_Scenario_03 -->
        <test-method is-config="true" signature="tearDown(java.lang.String)[pri:0, instance:com.LambdaTestFinal.TestNgTest1@4b2bac3f]" started-at="2023-08-31T11:36:12 IST" name="tearDown" finished-at="2023-08-31T11:36:13 IST" duration-ms="837" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test_02]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
 ****Title Not matched**** expected [Selenium Grid Online | Run Selenium Test On Cloud--] but found [Selenium Grid Online | Run Selenium Test On Cloud],
 **** Check Box already selected  **** expected [false] but found [true],
**** Alert Box message Not Matched! ****** expected [I am an alert box!--] but found [I am an alert box!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
 ****Title Not matched**** expected [Selenium Grid Online | Run Selenium Test On Cloud--] but found [Selenium Grid Online | Run Selenium Test On Cloud],
 **** Check Box already selected  **** expected [false] but found [true],
**** Alert Box message Not Matched! ****** expected [I am an alert box!--] but found [I am an alert box!]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.LambdaTestFinal.TestNgTest1.tearDown(TestNgTest1.java:149)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassConfigurations(TestMethodWorker.java:229)
at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:215)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:131)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.LambdaTestFinal.TestNgTest1 -->
    </test> <!-- Lambda Test02 -->
    <test started-at="2023-08-31T11:36:13 IST" name="Lambda Test03" finished-at="2023-08-31T11:36:31 IST" duration-ms="17816">
      <class name="com.LambdaTestFinal.TestNgTest1">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.LambdaTestFinal.TestNgTest1@bcec361]" started-at="2023-08-31T11:36:13 IST" name="setUp" finished-at="2023-08-31T11:36:23 IST" duration-ms="10697" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[82.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Windows 7]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Test_03]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="Test_Scenario_01(java.lang.String)[pri:0, instance:com.LambdaTestFinal.TestNgTest1@bcec361]" started-at="2023-08-31T11:36:23 IST" name="Test_Scenario_01" finished-at="2023-08-31T11:36:24 IST" duration-ms="1048" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://www.lambdatest.com/selenium-playground/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_Scenario_01 -->
        <test-method signature="Test_Scenario_02()[pri:0, instance:com.LambdaTestFinal.TestNgTest1@bcec361]" started-at="2023-08-31T11:36:24 IST" name="Test_Scenario_02" finished-at="2023-08-31T11:36:27 IST" duration-ms="2093" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_Scenario_02 -->
        <test-method signature="Test_Scenario_03(java.lang.String)[pri:0, instance:com.LambdaTestFinal.TestNgTest1@bcec361]" started-at="2023-08-31T11:36:27 IST" name="Test_Scenario_03" finished-at="2023-08-31T11:36:30 IST" duration-ms="3028" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://www.lambdatest.com/selenium-playground/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_Scenario_03 -->
        <test-method is-config="true" signature="tearDown(java.lang.String)[pri:0, instance:com.LambdaTestFinal.TestNgTest1@bcec361]" started-at="2023-08-31T11:36:30 IST" name="tearDown" finished-at="2023-08-31T11:36:31 IST" duration-ms="933" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test_03]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
 ****Title Not matched**** expected [Selenium Grid Online | Run Selenium Test On Cloud--] but found [Selenium Grid Online | Run Selenium Test On Cloud],
 **** Check Box already selected  **** expected [false] but found [true],
**** Alert Box message Not Matched! ****** expected [I am an alert box!--] but found [I am an alert box!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
 ****Title Not matched**** expected [Selenium Grid Online | Run Selenium Test On Cloud--] but found [Selenium Grid Online | Run Selenium Test On Cloud],
 **** Check Box already selected  **** expected [false] but found [true],
**** Alert Box message Not Matched! ****** expected [I am an alert box!--] but found [I am an alert box!]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.LambdaTestFinal.TestNgTest1.tearDown(TestNgTest1.java:149)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassConfigurations(TestMethodWorker.java:229)
at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:215)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:131)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.LambdaTestFinal.TestNgTest1 -->
    </test> <!-- Lambda Test03 -->
    <test started-at="2023-08-31T11:36:31 IST" name="Lambda Test04" finished-at="2023-08-31T11:36:56 IST" duration-ms="25375">
      <class name="com.LambdaTestFinal.TestNgTest1">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.LambdaTestFinal.TestNgTest1@40005471]" started-at="2023-08-31T11:36:31 IST" name="setUp" finished-at="2023-08-31T11:36:44 IST" duration-ms="13404" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Internet Explorer]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[11.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Windows 10]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Test_04]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="Test_Scenario_01(java.lang.String)[pri:0, instance:com.LambdaTestFinal.TestNgTest1@40005471]" started-at="2023-08-31T11:36:44 IST" name="Test_Scenario_01" finished-at="2023-08-31T11:36:47 IST" duration-ms="2834" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://www.lambdatest.com/selenium-playground/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_Scenario_01 -->
        <test-method signature="Test_Scenario_02()[pri:0, instance:com.LambdaTestFinal.TestNgTest1@40005471]" started-at="2023-08-31T11:36:47 IST" name="Test_Scenario_02" finished-at="2023-08-31T11:36:50 IST" duration-ms="3247" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_Scenario_02 -->
        <test-method signature="Test_Scenario_03(java.lang.String)[pri:0, instance:com.LambdaTestFinal.TestNgTest1@40005471]" started-at="2023-08-31T11:36:50 IST" name="Test_Scenario_03" finished-at="2023-08-31T11:36:55 IST" duration-ms="5208" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://www.lambdatest.com/selenium-playground/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_Scenario_03 -->
        <test-method is-config="true" signature="tearDown(java.lang.String)[pri:0, instance:com.LambdaTestFinal.TestNgTest1@40005471]" started-at="2023-08-31T11:36:55 IST" name="tearDown" finished-at="2023-08-31T11:36:56 IST" duration-ms="669" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test_04]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
 ****Title Not matched**** expected [Selenium Grid Online | Run Selenium Test On Cloud--] but found [Selenium Grid Online | Run Selenium Test On Cloud],
 **** Check Box already selected  **** expected [false] but found [true],
**** Alert Box message Not Matched! ****** expected [I am an alert box!--] but found [I am an alert box!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
 ****Title Not matched**** expected [Selenium Grid Online | Run Selenium Test On Cloud--] but found [Selenium Grid Online | Run Selenium Test On Cloud],
 **** Check Box already selected  **** expected [false] but found [true],
**** Alert Box message Not Matched! ****** expected [I am an alert box!--] but found [I am an alert box!]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.LambdaTestFinal.TestNgTest1.tearDown(TestNgTest1.java:149)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassConfigurations(TestMethodWorker.java:229)
at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:215)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:131)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.LambdaTestFinal.TestNgTest1 -->
    </test> <!-- Lambda Test04 -->
  </suite> <!-- Lambda Test Suite -->
</testng-results>
